# Generated by Django 5.2.17 on 2026-10-03 09:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import apps.tasks.models
import judge.core.profile


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0003_center_manager_role"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RunnerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True, verbose_name="slug")),
                ("title", models.CharField(max_length=100, verbose_name="nomi")),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("flutter", "Flutter"),
                            ("backend", "Backend"),
                            ("frontend", "Frontend"),
                        ],
                        max_length=20,
                        verbose_name="yoʻnalish",
                    ),
                ),
                (
                    "lane",
                    models.CharField(
                        choices=[
                            (
                                judge.core.profile.Lane["FAST"],
                                judge.core.profile.Lane["FAST"],
                            ),
                            (
                                judge.core.profile.Lane["HEAVY"],
                                judge.core.profile.Lane["HEAVY"],
                            ),
                        ],
                        max_length=10,
                        verbose_name="navbat",
                    ),
                ),
                ("config", models.JSONField(verbose_name="sozlamalar")),
                ("is_active", models.BooleanField(default=True, verbose_name="faol")),
            ],
            options={
                "verbose_name": "runner profil",
                "verbose_name_plural": "runner profillar",
                "ordering": ("title",),
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="nomi")),
                ("statement_md", models.TextField(verbose_name="shart (Markdown)")),
                (
                    "is_archived",
                    models.BooleanField(default=False, verbose_name="arxivda"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="authored_tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="muallif",
                    ),
                ),
                (
                    "center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tasks",
                        to="accounts.center",
                        verbose_name="markaz",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tasks",
                        to="tasks.runnerprofile",
                        verbose_name="profil",
                    ),
                ),
            ],
            options={
                "verbose_name": "topshiriq",
                "verbose_name_plural": "topshiriqlar",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="TaskVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveIntegerField(verbose_name="versiya")),
                (
                    "package",
                    models.FileField(
                        max_length=300,
                        upload_to=apps.tasks.models._package_path,
                        verbose_name="paket",
                    ),
                ),
                ("sha256", models.CharField(max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("building", "Yigʻilmoqda"),
                            ("build_failed", "Yigʻilmadi"),
                            ("ready", "Tayyor"),
                        ],
                        default="building",
                        max_length=20,
                    ),
                ),
                ("image_tag", models.CharField(blank=True, max_length=200)),
                ("build_log", models.TextField(blank=True)),
                ("build_errors", models.JSONField(blank=True, default=list)),
                ("manifest", models.JSONField(blank=True, null=True)),
                ("import_rules", models.JSONField(blank=True, null=True)),
                (
                    "starter",
                    models.FileField(
                        blank=True,
                        max_length=300,
                        upload_to=apps.tasks.models._starter_path,
                    ),
                ),
                (
                    "solution_wall_ms",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("warm_wall_ms", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "time_limit_s",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="vaqt limiti, s"
                    ),
                ),
                ("memory_limit_mb", models.PositiveIntegerField(blank=True, null=True)),
                ("runtime_info", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("built_at", models.DateTimeField(blank=True, null=True)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="tasks.task",
                    ),
                ),
            ],
            options={
                "verbose_name": "topshiriq versiyasi",
                "verbose_name_plural": "topshiriq versiyalari",
                "ordering": ("task", "-number"),
            },
        ),
        migrations.AddField(
            model_name="task",
            name="published_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="tasks.taskversion",
                verbose_name="eʼlon qilingan versiya",
            ),
        ),
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "opens_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="ochilish vaqti"
                    ),
                ),
                (
                    "deadline",
                    models.DateTimeField(blank=True, null=True, verbose_name="muddat"),
                ),
                (
                    "allow_late",
                    models.BooleanField(default=False, verbose_name="kechikib yuborishga ruxsat"),
                ),
                (
                    "max_attempts",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="urinishlar limiti"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assignments",
                        to="accounts.group",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assignments",
                        to="tasks.task",
                    ),
                ),
            ],
            options={
                "verbose_name": "biriktirish",
                "verbose_name_plural": "biriktirishlar",
                "ordering": ("-opens_at",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("task", "group"), name="tasks_assignment_once_per_group"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("deadline__isnull", True),
                            ("deadline__gt", models.F("opens_at")),
                            _connector="OR",
                        ),
                        name="tasks_assignment_deadline_after_opening",
                        violation_error_message="Muddat ochilish vaqtidan keyin boʻlishi kerak.",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("max_attempts__isnull", True),
                            ("max_attempts__gte", 1),
                            _connector="OR",
                        ),
                        name="tasks_assignment_attempts_positive",
                        violation_error_message="Urinishlar limiti kamida 1 boʻlsin yoki boʻsh qolsin.",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="taskversion",
            constraint=models.UniqueConstraint(
                fields=("task", "number"), name="tasks_version_number_unique"
            ),
        ),
    ]
