# Generated by Django 5.2.17 on 2026-10-03 08:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_center_roles_group"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="user",
            name="accounts_user_role_valid",
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("superadmin", "Superadmin"),
                    ("center_admin", "Markaz admini"),
                    ("center_manager", "Markaz menejeri"),
                    ("teacher", "Oʻqituvchi"),
                    ("student", "Oʻquvchi"),
                ],
                max_length=20,
                verbose_name="rol",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "role__in",
                        [
                            "superadmin",
                            "center_admin",
                            "center_manager",
                            "teacher",
                            "student",
                        ],
                    )
                ),
                name="accounts_user_role_valid",
                violation_error_message="Rolni tanlang.",
            ),
        ),
    ]
