# Generated by Django 5.2.17 on 2026-10-03 12:40

from django.db import migrations, models

import apps.accounts.models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_center_manager_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.FileField(
                blank=True,
                max_length=300,
                upload_to=apps.accounts.models._avatar_path,
                verbose_name="rasm",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="bio",
            field=models.TextField(blank=True, max_length=500, verbose_name="oʻzi haqida"),
        ),
        migrations.AddField(
            model_name="user",
            name="phone",
            field=models.CharField(blank=True, max_length=20, verbose_name="telefon"),
        ),
        migrations.AddField(
            model_name="user",
            name="telegram",
            field=models.CharField(blank=True, max_length=33, verbose_name="Telegram"),
        ),
    ]
