# Generated by Django 5.2.17 on 2026-10-03 09:27

from django.db import migrations, models

import apps.submissions.models
import judge.core.verdict


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "archive",
                    models.FileField(
                        max_length=300, upload_to=apps.submissions.models._archive_path
                    ),
                ),
                ("sha256", models.CharField(max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Navbatda"),
                            ("running", "Tekshirilmoqda"),
                            ("finished", "Tekshirildi"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                (
                    "verdict",
                    models.CharField(
                        blank=True,
                        choices=[
                            (
                                judge.core.verdict.Verdict["ACCEPTED"],
                                judge.core.verdict.Verdict["ACCEPTED"],
                            ),
                            (
                                judge.core.verdict.Verdict["WRONG_ANSWER"],
                                judge.core.verdict.Verdict["WRONG_ANSWER"],
                            ),
                            (
                                judge.core.verdict.Verdict["COMPILE_ERROR"],
                                judge.core.verdict.Verdict["COMPILE_ERROR"],
                            ),
                            (
                                judge.core.verdict.Verdict["TIME_LIMIT"],
                                judge.core.verdict.Verdict["TIME_LIMIT"],
                            ),
                            (
                                judge.core.verdict.Verdict["MEMORY_LIMIT"],
                                judge.core.verdict.Verdict["MEMORY_LIMIT"],
                            ),
                            (
                                judge.core.verdict.Verdict["RUNTIME_ERROR"],
                                judge.core.verdict.Verdict["RUNTIME_ERROR"],
                            ),
                            (
                                judge.core.verdict.Verdict["REJECTED"],
                                judge.core.verdict.Verdict["REJECTED"],
                            ),
                            (
                                judge.core.verdict.Verdict["SYSTEM_ERROR"],
                                judge.core.verdict.Verdict["SYSTEM_ERROR"],
                            ),
                        ],
                        max_length=20,
                    ),
                ),
                ("tests_total", models.PositiveIntegerField(default=0)),
                ("tests_passed", models.PositiveIntegerField(default=0)),
                (
                    "failed_test_index",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("failed_test_name", models.CharField(blank=True, max_length=500)),
                ("public_message", models.TextField(blank=True)),
                ("internal_log", models.TextField(blank=True)),
                ("wall_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("is_late", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "yechim",
                "verbose_name_plural": "yechimlar",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="SubmissionTestResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("index", models.PositiveIntegerField()),
                ("name", models.CharField(max_length=500)),
                ("stage", models.PositiveSmallIntegerField(default=1)),
                ("visibility", models.CharField(max_length=10)),
                (
                    "status",
                    models.CharField(choices=[("pass", "Oʻtdi"), ("fail", "Xato")], max_length=10),
                ),
                ("duration_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("message", models.TextField(blank=True)),
            ],
            options={
                "ordering": ("submission", "index"),
            },
        ),
    ]
