# Generated by Django 5.2.17 on 2026-10-03 09:27

import django.db.models.deletion
from django.db import migrations, models

import judge.core.profile


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("submissions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkerNode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("arch", models.CharField(max_length=20)),
                ("slots", models.JSONField(default=dict)),
                ("version", models.CharField(blank=True, max_length=100)),
                ("started_at", models.DateTimeField()),
                ("last_heartbeat", models.DateTimeField()),
            ],
            options={
                "verbose_name": "worker",
                "verbose_name_plural": "workerlar",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("build", "Image yigʻish"),
                            ("judge", "Tekshirish"),
                            ("rejudge", "Qayta tekshirish"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "lane",
                    models.CharField(
                        choices=[
                            (
                                judge.core.profile.Lane["FAST"],
                                judge.core.profile.Lane["FAST"],
                            ),
                            (
                                judge.core.profile.Lane["HEAVY"],
                                judge.core.profile.Lane["HEAVY"],
                            ),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "priority",
                    models.SmallIntegerField(
                        choices=[(0, "Build"), (10, "Judge"), (20, "Rejudge")]
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Navbatda"),
                            ("running", "Bajarilmoqda"),
                            ("done", "Tugadi"),
                            ("failed", "Xato"),
                        ],
                        default="queued",
                        max_length=10,
                    ),
                ),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("lease_expires_at", models.DateTimeField(blank=True, null=True)),
                ("worker_node", models.CharField(blank=True, max_length=100)),
                ("last_error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "submission",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to="submissions.submission",
                    ),
                ),
            ],
            options={
                "verbose_name": "vazifa (navbat)",
                "verbose_name_plural": "navbat",
                "ordering": ("priority", "created_at", "pk"),
            },
        ),
    ]
