# Generated by Django 5.2.17 on 2026-10-03 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("system", "0001_initial"),
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="task_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="jobs",
                to="tasks.taskversion",
            ),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                fields=["status", "lane", "priority", "created_at"],
                name="system_job_status_e8fe99_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="job",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("kind", "build"),
                        ("submission__isnull", True),
                        ("task_version__isnull", False),
                    ),
                    models.Q(
                        ("kind__in", ["judge", "rejudge"]),
                        ("submission__isnull", False),
                        ("task_version__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="system_job_target_matches_kind",
            ),
        ),
    ]
