"""The combined test file: every test file compiles once, as one suite (SPEC §3.3, step 3)."""

import re
from collections.abc import Sequence

from judge.packaging.zip_validator import ArchiveFile

COMBINED_TEST_PATH = "test/_ohw_all_test.dart"
# Test paths end up inside Dart string literals, so only plain characters are allowed.
_SAFE_TEST_PATH = re.compile(r"[A-Za-z0-9_./-]+")


def is_safe_test_path(path: str) -> bool:
    return bool(_SAFE_TEST_PATH.fullmatch(path)) and ".." not in path.split("/")


def combined_test_file(test_files: Sequence[str], test_import: str) -> ArchiveFile:
    """Import every test file and run its main() inside group('<path>', ...).

    The group keeps setUp/tearDown inside their own file; the dart_json parser strips the
    group name from test names. ``test_files`` are relative to test/, in run order.
    """
    unsafe = [path for path in test_files if not is_safe_test_path(path)]
    if unsafe:
        raise ValueError(f"unsafe test file paths: {unsafe}")
    lines = [
        "// Generated by Online Home Work. Do not edit.",
        f"import '{test_import}';",
        "",
        *(f"import '{path}' as f{i};" for i, path in enumerate(test_files)),
        "",
        "void main() {",
        *(f"  group('{path}', f{i}.main);" for i, path in enumerate(test_files)),
        "}",
        "",
    ]
    return ArchiveFile(COMBINED_TEST_PATH, "\n".join(lines).encode())
