import pytest

from judge.packaging.combined_tests import (
    COMBINED_TEST_PATH,
    combined_test_file,
    is_safe_test_path,
)


def test_combined_file_wraps_every_test_file_in_a_group() -> None:
    combined = combined_test_file(
        ["public/01_cart_test.dart", "hidden/02_discount_test.dart"], "package:test/test.dart"
    )

    assert combined.path == COMBINED_TEST_PATH
    assert combined.data.decode() == (
        "// Generated by Online Home Work. Do not edit.\n"
        "import 'package:test/test.dart';\n"
        "\n"
        "import 'public/01_cart_test.dart' as f0;\n"
        "import 'hidden/02_discount_test.dart' as f1;\n"
        "\n"
        "void main() {\n"
        "  group('public/01_cart_test.dart', f0.main);\n"
        "  group('hidden/02_discount_test.dart', f1.main);\n"
        "}\n"
    )


def test_flutter_profile_imports_flutter_test() -> None:
    combined = combined_test_file(["public/a_test.dart"], "package:flutter_test/flutter_test.dart")

    assert "import 'package:flutter_test/flutter_test.dart';" in combined.data.decode()


@pytest.mark.parametrize(
    "path",
    [
        "public/it's_test.dart",
        "public/$x_test.dart",
        "public/a\\b_test.dart",
        "public/../x_test.dart",
        "public/a b_test.dart",
        "",
    ],
)
def test_unsafe_paths_never_reach_dart_source(path: str) -> None:
    assert not is_safe_test_path(path)
    with pytest.raises(ValueError, match="unsafe"):
        combined_test_file([path], "package:test/test.dart")
